# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7067d7ebf88ef5011686185a0a7a1a9e9c597621a748c23d62129efd1d26354ef41c7b703f2795abcf356a683729eb5ae5c3873721c149b3cfe76da5dedb911

test:
  secret_key_base: 6ba6ccc777e6afd9bf0212ece6c067a002997eae3465d0b3c9f68fa2d3896a97692b0c22a3db4acc3d908696cdedd32af085b8d5c164a8e022f8af0eb1604927

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
